### ISSUE TITLE
cool!

### ISSUE THREAD

**Issue by aquynh** [samdmarshall/machodiff#1]
this looks like a nice project,but how to use that? unfortunately there is not much info in README on how to build & use it.

keep it up, cheers.

**Comment by samdmarshall** [comment]
Yes, this project died on me and I figured that it was better to open source it as (hopefully) my last mach-o binary parser for others to use and take advantage of the code. it should build out of the box using Xcode 6 or newer.

**Comment by aquynh** [comment]
I see. Cool, lets start with a README first?
